# This file marks the migration as applied
# Prisma Migrate uses this file to detect if a migration has been applied

migration_name = "20250421213325_add_iconurl_to_categoryfilter"
checksum = "c3ae7ab72d8a89baa11f40fa71a9a33d73e0d4a7d0a4fd20562c0be502fc9eb6" 